const array = [
  {
    userId: 1,
    id: 1,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 2,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 3,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 4,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 5,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 6,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 7,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 8,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 9,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 10,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 11,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 12,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 13,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 14,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 15,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 16,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 17,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 18,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 19,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 20,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 21,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
  {
    userId: 1,
    id: 22,
    title: "Lazy loading",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel illum",
  },
];
